version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: avito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5441
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
